### PR TITLE
add android xamarin support

### PR DESCRIPTION
**Pull request by pgaubatz**
warning: not tested yet, but may magically work anyways.

### CODE REVIEW

**Comment by mrvnagstn** [comment]
i will try it, can you tell me which .so file i should use? is there a special one for android or can i use one of the linux ones? thank you

**Comment by pgaubatz** [comment]
Hi @mrvnagstn, thanks for testing!
You'll have to use the android version of the client. more precisely, the android archive (.aar file) will have to be imported in your project's dependencies. Maybe the following guide may be helpful: https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar

**Comment by mrvnagstn** [comment]
@pgaubatz thank you, but i told @prempador already that i am getting following error if i am bind the new android archive into a xamarin binding:
BINDINGSGENERATOR : warning BG8601: No packages found.

Build action is set to "LibraryProjectZip". 
What i am doing wrong?

**Comment by mrvnagstn** [comment]
Okay, another handling worked:

1)
downloaded this branch -> open project -> add compiler directive "Android" -> build SDK project

2)
added "fiskaly-dotnet-sdk" with precompiled "Android" to link to AndroidClient to my xamarin project

3)
added extracted .so files from your .aar for all ABIs and set the build action to "AndroidNativeLibrary"

4)
"client.ConfigureClient()" is working and if i am trying to add a transaction i got this:
{{
	Message: "Invalid params
	",
	Code: "-32602"
	 Error: {
  "Offset": 1
}
}}
[ERROR] 2020/04/15 13:17:36 request.go:154: invalid character 'e' looking for beginning of value

**Comment by prempador** [comment]
Thank you very much @mrvnagstn for testing this out, we are in no way professionals with Xamarin.

**Comment by pgaubatz** [comment]
Hey @mrvnagstn!

Thanks for finding a way for making this thing work!

> added extracted .so files from your .aar for all ABIs and set the build action to "AndroidNativeLibrary"

Although I am glad that this approach works, I am not really convinced that this is the most elegant way of solving this problem.
I quick google search lead to me this page: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process#androidaarlibrary
I believe it should be sufficient to just reference the downloaded .aar file in your build process as a `AndroidAarLibrary`. Do you think you could give this a try as well?

**Comment by mrvnagstn** [comment]
@pgaubatz yes, i will check it - i think it could probably solve the issue to import the *.so files manually but actually i cannot use your nuget-dotnet-sdk because its compiled without the "Android" directive. may you have to deploy a second one for Android?
and another view:
if i "reviewed" it correctly your methods in your android archive are non-public or obfuscated so the binding generator cannot use this. (https://forums.xamarin.com/discussion/84619/binding-android-library-not-generate-all-class) 
or at least: the AndroidArchive on Xamarin can be used only for importing the *.so files and via the dotnet-sdk(with android directive^^) will be the methods in *.so files invoked?

another point, not directly attaching this request but actually i cannot use our nuget on windows because its not signed with strong name - could you handle this? we need this for clickonce deployment.

**Comment by mrvnagstn** [comment]
@pgaubatz good morning, the check with only included android archive with your proposed build action works as well. no extraction of *.so files needed anymore.

but the two points with the nugets would be nice if you could solve it:

- deploying second fiskaly-dotnet-sdk with "Android" compiler directive 

- signing the windows fiskaly-dotnet-sdk assembly with strong name, so that is isnt required for us to compile the sdk ourself (https://docs.microsoft.com/de-de/dotnet/standard/assembly/sign-strong-name#create-and-sign-an-assembly-with-a-strong-name-by-using-visual-studio)

thank u :)

**Comment by mrvnagstn** [comment]
do you have an update for me?

**Comment by prempador** [comment]
I think @auxdevelopment is working on it. Maybe he can tell you more!

**Comment by mrvnagstn** [comment]
hi @auxdevelopment, can you? :)

**Comment by auxdevelopment** [comment]
Android support will be included with the next client release (should be happening today).

**Pull request merged**
